<<<<<<< HEAD
# Generated by Django 3.2.23 on 2024-09-04 17:17
=======
# Generated by Django 3.2.23 on 2024-09-04 14:44
>>>>>>> 84752628221f491717b54f099bfa9eef86b204c2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('posts', '0005_alter_post_category'),
=======
        ('posts', '0001_initial'),
>>>>>>> 84752628221f491717b54f099bfa9eef86b204c2
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
